"""Add analytics schema: Vehicle, ServiceCategory, labor tracking, timestamps, cost fields

Revision ID: 806b2bed5871
Revises:
Create Date: 2026-01-03 00:31:29.150621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '806b2bed5871'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('part_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('reorder_point', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
        batch_op.create_unique_constraint(None, ['part_number'])

    with op.batch_alter_table('mechanics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    with op.batch_alter_table('service_inventories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_at_service', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cost_at_service', sa.Float(), nullable=True))

    with op.batch_alter_table('service_tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicle_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('labor_hours', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('labor_rate', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('mileage', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 'vehicles', ['vehicle_id'], ['id'])
        batch_op.create_foreign_key(None, 'service_categories', ['category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_tickets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('notes')
        batch_op.drop_column('mileage')
        batch_op.drop_column('labor_rate')
        batch_op.drop_column('labor_hours')
        batch_op.drop_column('completed_at')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('status')
        batch_op.drop_column('category_id')
        batch_op.drop_column('vehicle_id')

    with op.batch_alter_table('service_inventories', schema=None) as batch_op:
        batch_op.drop_column('cost_at_service')
        batch_op.drop_column('price_at_service')

    with op.batch_alter_table('mechanics', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('created_at')
        batch_op.drop_column('reorder_point')
        batch_op.drop_column('part_number')
        batch_op.drop_column('category')
        batch_op.drop_column('cost')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
